library: /home/rhys/BeetLibrary.db
directory: /home/rhys/BeetLibrary
plugins: bpd chroma duplicates edit fetchart fromfilename lyrics lastgenre mbsync web

art_filename: albumart
chroma:
    auto: yes
ignore:
  .
  ..
import:
    autotag: yes
    copy: yes
    duplicate_action: remove
    languages: en
    log: beetslog.txt
    verbose: no
    write: yes
lyrics:
    auto: no
paths:
    default: $albumartist/$album/$track $title
    singleton: Singletons/$artist - $title
    comp: Compilation/$album/$track $title
    albumtype:soundtrack: Soundtracks/$album/$track $title
threaded: yes
per_disc_numbering: yes
ui:
    color: yes
