library: /home/rhys/BeetLibrary.db
directory: /home/rhys/BeetLibrary
plugins: bpd chroma duplicates fetchart fromfilename lyrics lastgenre web

art_filename: albumart
chroma:
    auto: yes
ignore:
  .
  ..
import:
    copy: yes
    write: yes
    log: beetslog.txt
    verbose: no
lyrics:
    auto: yes
paths:
    default: $albumartist/$album/$track $title
    singleton: Singletons/$artist - $title
    comp: Compilation/$album/$track $title
    albumtype:soundtrack: Soundtracks/$album/$track $title
threaded: yes
per_disc_numbering: yes
ui:
    color: yes
